server:
  port: 9200

spring:
  application:
    name: webcanvas-service
  datasource:
    url: jdbc:mysql://localhost:3306/webcanvas_db
    username: webcanvas_app
    password: webcanvas_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
      connection-test-query: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        messaging: debug

application:
  domain:
    game:
      # 게임 방 입장 최대 정원
      game-room-capacity: 8
      # 게임 방 생성중 입장코드 충돌 발생 시 재생성 시도 최대 횟수
      join-code-max-conflict-count: 10
      # 게임 방의 입장 코드 길이
      join-code-length: 10;
#  security:
#    web:
#    web-socket:


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha