##### 서버 포트 설정 #####
server:
  port: 9200

##### 스프링 설정 #####
spring:
  application:
    name: webcanvas-service
  datasource:
    url: jdbc:mysql://localhost:3306/webcanvas_db
    username: webcanvas_app
    password: webcanvas_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
      connection-test-query: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000


##### 로깅 레벨 관련 설정 #####
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: debug
        web: debug
        messaging: debug
    com.bb.webcanvasservice: debug

##### 애플리케이션 설정 #####
application:
  sequence:
      list:
        - "KOREAN_NOUN"
        - "KOREAN_ADJECTIVE"
  domain:
    game:
      # 게임 방 입장 최대 정원
      game-room-capacity: 8
      # 게임 방 생성중 입장코드 충돌 발생 시 재생성 시도 최대 횟수
      join-code-max-conflict-count: 10
      # 게임 방의 입장 코드 길이
      join-code-length: 10
      game-room-user-colors:
        - "#ff3c00"
        - "#0042ff"
        - "#1e9000"
        - "#f2cb00"
        - "#8400a8"
        - "#00c8c8"
        - "#ff68ff"
        - "#969696"
      game-room-user-nickname-nouns:
        - "여우"
        - "수달"
        - "늑대"
        - "고양이"
        - "부엉이"
        - "다람쥐"
        - "호랑이"
        - "너구리"
    dictionary:
      source:
        data-url: https://github.com/bbyuk/web-game-platform/releases/download/v0.1.3/elementary_korean.zip
        # download / local
        location: local
  security:
    secret-key: E2fhmOQToTXJCtVmyCc8AzwQK2bNC9VJBMlBXi/bNEQ=
    ## 단위 초 (s)
    # 15분 (15 * 60)
    access-token-expiration: 900
    # 14일 (14 * 24 * 60 * 60)
    refresh-token-expiration: 1209600
    # 3일 (3 * 24 * 60 * 60)
    refresh-token-reissue-threshold: 259200
    white-list:
      - /swagger-ui/**
      - /api-docs/**
      - /auth/login
      - /auth/refresh
      - /ws/**
    cookie:
      refresh-token: refresh-token

##### WebSocket 관련 설정 #####
websocket:
  # 연결 엔드포인트
  endpoint: /ws/canvas
  # 활성화 브로커 목록 (message destination)
  topic:
    main:
      game-room: /room
      game-session: /session
    sub:
      canvas: canvas
      chat: chat
  # CORS 허용 목록
  allowed-origin-patterns:
    - "*"
  # 비정상 접근 제한 횟수
  abnormal-access-limit: 5

##### 비동기 관련 설정 #####
async:
  executor:
    # 기본 스레드 개수
    core-pool-size: 4
    # 최대 스레드 개수
    max-pool-size: 8
    # 작업 큐 용량 (초과시 새로운 스레드 생성)
    queue-capacity: 100
    # 생성될 스레드 이름 접두어
    thread-name-prefix: "async-task-executor-"

##### Swagger API 문서 관련 설정 #####
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha