server:
  port: 9200

spring:
  application:
    name: webcanvas-service
  datasource:
    url: jdbc:mysql://localhost:3306/webcanvas_db
    username: webcanvas_app
    password: webcanvas_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP
      connection-test-query: "SELECT 1"

logging:
  level:
    org:
      springframework:
        web:
          socket: debug
        messaging: debug
